spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    oracle:
      url: jdbc:oracle:thin:@1.2.3.4:1521:SID?
      username: oracle_user
      password: oracle_pw
      driver-class-name: oracle.jdbc.OracleDriver

    mysql:
      url: jdbc:mysql://5.6.7.8:3306/new_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: mysql_user
      password: mysql_pw
      driver-class-name: com.mysql.cj.jdbc.Driver